runtime: php
env: flex

runtime_config:
  document_root: public

skip_files:
  -.env

env_variables:
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:47L+a5BWI2VyIaOsMLLo4XwpvOQm3PtHXy9AHRHWDjQ=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: icommerce_sandbox2
  DB_USERNAME: 9cloudNg
  DB_PASSWORD: N1n3C10ud@!^&
  DB_SOCKET: "/cloudsql/icitng:europe-west6:icommerce-uat"

beta_settings:
  cloud_sql_instances: "icitng:europe-west6:icommerce-uat"
